# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
import numpy as np

In [16]:



#Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[5,10,15,20,4]])
arr1[0:,2:3]=1
print(arr1)

[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]
 [ 5 10  1 20  4]]


In [19]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12],[13,14,15,16]])
np.fill_diagonal(arr2, 0)
print(arr1)

[[ 0  2  1  4  5]
 [ 6  0  1  9 10]
 [11 12  0 14 15]
 [16 17  1  0 20]
 [ 5 10  1 20  0]]


In [6]:
    #1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr = np.arange(1, 37).reshape(6, 6)


arr_new=arr[2:5,1:4]
print(arr_new)

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [10]:
arr1 = np.random.randint(1, 100, (3, 4))
arr2 = np.random.randint(1, 100, (3, 4))



print('Addition=',arr1+arr2)

print('Substraction=',arr1-arr2)

print('Multiplication=',arr1*arr2)

print('Divison=',arr1/arr2)

Addition= [[117  86  38 154]
 [126  81  76 131]
 [155  73 109 122]]
Substraction= [[-55 -38   6  30]
 [ 52 -51  -6  11]
 [-25 -21 -13 -56]]
Multiplication= [[2666 1488  352 5704]
 [3293  990 1435 4260]
 [5850 1222 2928 2937]]
Divison= [[0.36046512 0.38709677 1.375      1.48387097]
 [2.40540541 0.22727273 0.85365854 1.18333333]
 [0.72222222 0.55319149 0.78688525 0.37078652]]


In [4]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


arr1=np.random.randint(1,16,(4,4))
arr2=np.random.randint(1,16,(4,4))


row_sum = arr1.sum(axis=1)
col_sum = arr1.sum(axis=0)

print(row_sum)
print(col_sum)

[27 48 29 31]
[30 45 25 35]


In [19]:
#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


arr1=np.random.randint(1,100,(5,5))

#mean

mean=arr1.mean()
print('Mean =',mean)

#median

median=np.median(arr1)
print('Median =',median)


#standard deviation

standard_deviation=np.std(arr1)
print('Standard_Deviation =',standard_deviation)


#variance of the array.

variance=np.var(arr1)
print('Variance =',variance)

Mean = 54.72
Median = 59.0
Standard_Deviation = 27.109437471109576
Variance = 734.9215999999999


In [22]:
#Normalization of data

N_m =(arr1-mean)/standard_deviation

print('N_m=',N_m)

N_m= [[-0.94874709  0.37920374 -1.79716012  1.04317915 -1.57583499]
 [ 1.22761677  0.41609126  1.22761677  0.01032851  0.74807897]
 [ 0.85874154  0.1578786   1.08006668 -0.65364691 -0.76430948]
 [-0.46920929  1.1169542   1.04317915 -1.7602726   0.12099108]
 [-1.2807348   0.56364135 -0.83808452  1.08006668 -0.98563462]]


In [25]:
#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(1,100,(3,))

print(arr1)
print(arr2)

print('Sum =',arr1+arr2)

[[27 17 53]
 [79 60 70]
 [19 26 83]]
[54 43 52]
Sum = [[ 81  60 105]
 [133 103 122]
 [ 73  69 135]]


In [ ]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


arr1=np.random.randint(1,100,(4,4))
arr2=np.random.randint(1,100,(4,))

arr2.reshape(-1,4)




[[23 51 54 59]
 [27 20 43 11]
 [43 47 85 31]
 [13 59 12 19]]
[48 90  4 92]


In [35]:
#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


arr1=np.random.randint(1,100,(3,3))

# Determinant
det_A = np.linalg.det(arr1)
print('Determinant =',det_A)

# Inverse
inv_A = np.linalg.inv(arr1)

print('Inverse =',inv_A)

# Eigenvalues
eigenvalues = np.linalg.eigvals(arr1)
print('Eigenvalues =',eigenvalues)

Determinant = -72630.00000000001
Inverse = [[ 0.02478315  0.00272615 -0.01363073]
 [ 0.01149663 -0.03817982  0.02423241]
 [-0.02099683  0.03380146 -0.00234063]]
Eigenvalues = [136.75888973  29.96467065 -17.72356038]


In [39]:
 #Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
 
arr1=np.random.randint(1,100,(2,3))
arr2=np.random.randint(1,100,(3,2))
result = np.dot(arr1, arr2) 

print('matrix_multiple =',result)

matrix_multiple = [[ 8709  2347]
 [11530  3612]]


In [ ]:
#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

arr1 = np.arange(1, 10).reshape(3, 3)

print(arr1)

arr1=arr1.reshape(1,9)
print(arr1)

arr1=arr1.reshape(9,1)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [57]:
#Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

 
arr1=np.random.randint(1,100,(5,5))

arr1=arr1.ravel()

print(arr1)

arr1=arr1.reshape(5,5)
print(arr1)



[57 92 25  4 80 32 64 44 83 55  8 31 13 49 62 10 86 21 55 71 87 16 87 23
 53]
[[57 92 25  4 80]
 [32 64 44 83 55]
 [ 8 31 13 49 62]
 [10 86 21 55 71]
 [87 16 87 23 53]]


In [59]:
#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


arr1 = np.random.randint(1, 100, (5, 5))

# Fancy indexing to extract corner elements
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]

print(corners)

[ 1  6 31 36]


In [70]:
#Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

arr1 = np.arange(1,17).reshape(4,4)

arr1[arr1<10]=10

print(arr1)


[[10 10 10 10]
 [10 10 10 10]
 [10 10 11 12]
 [13 14 15 16]]


In [71]:
#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
import numpy as np

# Define data type for structured array
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# Create structured array with some data
data = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 22, 70.2),
    ('Charlie', 30, 68.0),
    ('David', 28, 75.0)
], dtype=dtype)

# Sort array by 'age'
sorted_data = np.sort(data, order='age')

print("Original array:\n", data)
print("\nSorted by age:\n", sorted_data)


Original array:
 [('Alice', 25, 55.5) ('Bob', 22, 70.2) ('Charlie', 30, 68. )
 ('David', 28, 75. )]

Sorted by age:
 [('Bob', 22, 70.2) ('Alice', 25, 55.5) ('David', 28, 75. )
 ('Charlie', 30, 68. )]


In [72]:
import numpy as np

# Define structured array with 'x' and 'y' as integers
dtype = [('x', 'i4'), ('y', 'i4')]

# Create structured array with some points
points = np.array([
    (1, 2),
    (4, 6),
    (7, 8)
], dtype=dtype)

# Extract x and y as regular arrays
x = points['x']
y = points['y']

# Compute Euclidean distance between each pair
n = len(points)
distances = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        distances[i, j] = np.sqrt((x[i] - x[j])**2 + (y[i] - y[j])**2)

print("Points:\n", points)
print("\nEuclidean distance matrix:\n", distances)


Points:
 [(1, 2) (4, 6) (7, 8)]

Euclidean distance matrix:
 [[0.         5.         8.48528137]
 [5.         0.         3.60555128]
 [8.48528137 3.60555128 0.        ]]


In [73]:
import numpy as np

# Create 4x4 array with random integers from 1 to 20
arr = np.random.randint(1, 20, (4, 4))

# Mask elements greater than 10
masked_arr = np.ma.masked_greater(arr, 10)

# Compute sum of unmasked elements
sum_unmasked = masked_arr.sum()

print("Original array:\n", arr)
print("\nMasked array:\n", masked_arr)
print("\nSum of unmasked elements:", sum_unmasked)


Original array:
 [[14  7 19  8]
 [12  5 14  5]
 [14  1 19 18]
 [13 11  4 16]]

Masked array:
 [[-- 7 -- 8]
 [-- 5 -- 5]
 [-- 1 -- --]
 [-- -- 4 --]]

Sum of unmasked elements: 30


In [74]:
import numpy as np

# Create a 3x3 array with random integers from 1 to 20
arr = np.random.randint(1, 20, (3, 3))

# Mask the diagonal elements
masked_arr = np.ma.masked_array(arr, mask=np.eye(3, dtype=bool))

# Compute mean of unmasked elements
mean_unmasked = masked_arr.mean()

# Fill masked (diagonal) elements with mean
filled_arr = masked_arr.filled(mean_unmasked)

print("Original array:\n", arr)
print("\nMasked array:\n", masked_arr)
print("\nMean of unmasked elements:", mean_unmasked)
print("\nArray after replacing masked elements with mean:\n", filled_arr)


Original array:
 [[ 7  2 12]
 [ 1  2 14]
 [10 10 11]]

Masked array:
 [[-- 2 12]
 [1 -- 14]
 [10 10 --]]

Mean of unmasked elements: 8.166666666666666

Array after replacing masked elements with mean:
 [[ 8  2 12]
 [ 1  8 14]
 [10 10  8]]
